<template>
  <svg
    class="white-logo"
    width="113"
    height="137"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
  >
    <image
      xlink:href="/LogoBlack.svg"
      width="113"
      height="137"
    />
  </svg>
</template>
